### ISSUE TITLE
AttributeError: 'Resolver' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by Rozendantz** [darkoperator/dnsrecon#190] opened 2021-05-17 04:51 UTC
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**

dnsrecon -d www.facebook.com
[*] std: Performing General Enumeration against: www.facebook.com...
Traceback (most recent call last):
  File "/usr/share/dnsrecon/dnsrecon.py", line 1763, in <module>
    main()
  File "/usr/share/dnsrecon/dnsrecon.py", line 1650, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex,
  File "/usr/share/dnsrecon/dnsrecon.py", line 925, in general_enum
    check_wildcard(res, domain)
  File "/usr/share/dnsrecon/dnsrecon.py", line 189, in check_wildcard
    ips = res.get_a(testname)
  File "/usr/share/dnsrecon/lib/dnshelper.py", line 118, in get_a
    answers = self.get_answers('A', host_trg)
  File "/usr/share/dnsrecon/lib/dnshelper.py", line 82, in get_answers
    return self._res.resolve(addr_, type_, tcp=self._is_tcp)
AttributeError: 'Resolver' object has no attribute 'resolve'

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: install tool on Arch Linux from Blackarch repo (have no been able to test with other Linux)
2. run with any domain: dnsrecon -d <any domain>
3. See error

**Expected behaviour**
Expected it to work

**System Information (System that tool is running on):**
 - OS: Arch Linux 
 - 5.10.33-1-lts

**Additional context**
Python is 3.9.5
I thought this may be an issue with extended ping (some of my VPN endpoints get up to ~100ms range), so I switched to a closer VPN gateway (8ms) and still the problem persists. Also tried playing with --lifetime flag but nothing changed. Then I did a full system upgrade just to be sure, still nothing.

**Comment by someotherkyle** [comment] 2021-06-02 22:25
I am experiencing the same issue. I don't have any ideas for fixing but wanted to comment to confirm that it is reproducible on my machine.

**Comment by L1ghtn1ng** [comment] 2021-06-02 22:27
This should be fixed in master, need to make sure you are using the latest release
________________________________

**Comment by someotherkyle** [comment] 2021-06-03 13:42
`pacman -Si dnsrecon `

```
Repository      : blackarch
Name            : dnsrecon
Version         : 2:0.10.1-1
Description     : Python script for enumeration of hosts, subdomains and emails from a given domain using google.
Architecture    : any
URL             : https://github.com/darkoperator/dnsrecon
Licenses        : custom
Groups          : blackarch  blackarch-recon
Provides        : None
Depends On      : python  python-netaddr  python-dnspython  python-lxml
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 499.16 KiB
Installed Size  : 1512.28 KiB
Packager        : Levon Kayan <noptrix@nullsecurity.net>
Build Date      : Sat Apr 10 16:37:26 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
Appears to match the release on 4/5 10.1

**Comment by someotherkyle** [comment] 2021-06-06 19:29
Strangely enough, version 0.10.0 packaged with kali works fine on my vm -- will try rolling back to 0.10.0 on blackarch to see if the issue persists

**Comment by someotherkyle** [comment] 2021-06-07 18:51
Confirmed that this issue is present in 0.10.1 and is not present in 0.10.0 on blackarch.

**Comment by honuonhval** [comment] 2021-06-30 06:05
python-dnspython version (community, 1.16.0-3 as of today June 30th, 2021) in Arch Linux (and most likely BlackArch and ArcoLinux) uses deprecated dns.resolver.Resolver.query.  Once you install python-dnspython-git from AUR and it should work.

**Comment by L1ghtn1ng** [comment] 2021-06-30 08:00
Yeah that will be the problem
________________________________

**Comment by L1ghtn1ng** [comment] 2021-06-30 08:10
Thanks for that, had not managed to dig into it yet but yes that is the cause for this issue.

**Comment by L1ghtn1ng** [comment] 2021-07-01 22:59
You can also install it here https://github.com/rthalley/dnspython but recommend using a virtualenv but using AUR to install the new dnspython version would be easier

**Closed by L1ghtn1ng** 2021-07-01 22:59 UTC

**Comment by shaworee** [comment] 2022-10-15 17:30
Thank you all for your comments. I'm a mere network administrator, so it would take me a little while to get these things up and running.
For all non-pythoners, here are steps that has worked for me:
1) Check your dnspython version with command pip show dnspython
2) If your version is different with github version (at the time version is listed here https://github.com/rthalley/dnspython#readme)
3) If version is not the same. You can install uninstall old package and install new one with these commands:
pip uninstall dnspython
pip install git+https://github.com/rthalley/dnspython
4) now package dnsrecon works without previous error (AttributeError: 'Resolver' object has no attribute 'resolve')

Hope this helps someone
