### ISSUE TITLE
AttributeError: 'Resolver' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by wvdongen** [darkoperator/dnsrecon#146] opened 2020-11-02 15:50 UTC
`dnsrecon.py --domain example.com -t std --json file.json -n 8.8.8.8`

Error:

```
Traceback (most recent call last):
  File "/dnsrecon/dnsrecon.py", line 1691, in <module>
    main()
  File "/dnsrecon/dnsrecon.py", line 1415, in main
    if check_nxdomain_hijack(entry):
  File "/dnsrecon/dnsrecon.py", line 208, in check_nxdomain_hijack
    answers = res.resolve(test_name, record_type, tcp=True)
AttributeError: 'Resolver' object has no attribute 'resolve'
```

Using the code in the master branch.

**Comment by tschiew** [comment] 2020-12-21 09:06
I get the same error. 

I use version 0.9.1+git20200921-1 on Kali.

Any hint how to fix it?

**Comment by tschiew** [comment] 2020-12-21 10:58
Update: In my case it works a bit better after downloading the 0.9.1 from github (instead of using the version from the kali repo). 

The "nxdomain" error does not appear anymore. Now occurs "NoneType object is not iterable".

But it seems that developing has been stopped for this software.

**Comment by darkoperator** [comment] 2020-12-21 11:15
Really? With commits from this year ;) it has not stopped. Can you provide more details as to what command line combination you used?

**Comment by tschiew** [comment] 2020-12-21 11:39
Ok, great! :) I merely thought about a stopped development because the latest release was in 04/2019.

I used the following command: ```dnsrecon-0.9.1# python3.8 dnsrecon.py -n 10.1.1.213 -d victim.local -a```

The result was:
```
[*] Performing General Enumeration of Domain: victim.local
[*] Checking for Zone Transfer for victim.local name servers
[*] Resolving SOA Record
[-] Error while resolving SOA record.
[*] Resolving NS Records
[-] Could not Resolve NS Records
[*] Removing any duplicate NS server IP Addresses...
[*] Checking for Zone Transfer for victim.local name servers
[*] Resolving SOA Record
[-] Error while resolving SOA record.
[*] Resolving NS Records
[-] Could not Resolve NS Records
[*] Removing any duplicate NS server IP Addresses...
Traceback (most recent call last):
  File "dnsrecon.py", line 1788, in <module>
    main()
  File "dnsrecon.py", line 1748, in main                                                                                                                                                                                                   
    returned_records.extend(std_enum_records)                                                                                                                                                                                              
TypeError: 'NoneType' object is not iterable            
```

**Comment by pqlx** [comment] 2021-01-07 14:59
This problem is caused by versioning issues with the `dnspython` module. Functionality works as intended with `dnspython>=2.0.0` but not with version `1.x.x` (i.e `1.16.0`).

**Comment by pqlx** [comment] 2021-01-07 15:04
I've attached a pull request which aims to fix this issue:

https://github.com/darkoperator/dnsrecon/pull/150

**Comment by L1ghtn1ng** [comment] 2021-01-14 13:51
This should be fixed in master now, thanks @pqlx

**Closed by L1ghtn1ng** 2021-01-14 13:51 UTC
