### ISSUE TITLE
NameError: global name 'goo_result_process' is not defined

### ISSUE THREAD

**Issue by Veritas83** [darkoperator/dnsrecon#71] opened 2017-10-27 00:00 UTC
version: 0.8.11 (Python 2.7.14)
cmdline: dnsrecon -t std,srv,goo,zonewalk,brt -D /usr/share/dnsrecon/namelist.txt -g -z --threads 1 --lifetime 10 -d redacted.com > dnsrecon-redacted.com.txt

Traceback (most recent call last):
  File "./dnsrecon.py", line 1670, in <module>
    main()
  File "./dnsrecon.py", line 1507, in main
    std_enum_records = general_enum(res, domain, xfr, goo, bing, spf_enum, do_whois, zonewalk)
  File "./dnsrecon.py", line 1046, in general_enum
    goo_rcd = goo_result_process(res, scrape_google(domain))
NameError: global name 'goo_result_process' is not defined

**Comment by darkoperator** [comment] 2017-10-27 00:44
Will tae a look, but out of cusiosity why are you redirecting the output to a file when it can save data to JSON, CSV or Sqlite3 file which are more flexible?

Also weird that is say Line 1670 when dnsrecon is 1665 lines long. it looks as it is importing one of the libs incorrectly. Have you modifed the code from Github in any way? on what version of linux is this?

**Comment by Veritas83** [comment] 2017-10-27 02:29
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux

afaik I haven't modified the code. But i did open the dnsrecon.py at least once or twice to check i was running the latest version.

I'm outputting to a file because I'm calling dnsrecon in a bash script with a bunch of other tools and i just want regular text files as the output

I'll pastebin the copy i have here. https://pastebin.com/KyNHL6mU

**Comment by Veritas83** [comment] 2017-10-27 02:45
For good measure. I completely removed dnsrecon and cloned the git again just now. This is the result.

```
root@kali:~/Scans# dnsrecon -t std,srv,goo,zonewalk,brt -D /usr/share/dnsrecon/namelist.txt -g -z --threads 1 --lifetime 10 -d redacted.com > dnsrecon-redacted.com.txt
Traceback (most recent call last):
  File "./dnsrecon.py", line 1665, in <module>
    main()
  File "./dnsrecon.py", line 1502, in main
    std_enum_records = general_enum(res, domain, xfr, goo, bing, spf_enum, do_whois, zonewalk)
  File "./dnsrecon.py", line 1041, in general_enum
    goo_rcd = goo_result_process(res, scrape_google(domain))
NameError: global name 'goo_result_process' is not defined
```

**Comment by darkoperator** [comment] 2017-10-27 02:46
This makes it clearer. Seems when Kali packaged the file they modified it.

**Comment by darkoperator** [comment] 2017-10-27 02:49
If you cloned it should you not be running it from the cloned folder and doing ./dnsrecon.py ... ? The issue is that it is not loading the google library for the tool where the method resides

**Comment by Veritas83** [comment] 2017-10-27 02:57
Just tried that, the output was the same. Kali is definitely modifying. I removed the git clone and tried to install again via apt see if anything changed. the 1670 line number returns.

**Comment by clmntb** [comment] 2017-11-13 09:10
It seems that your python2 version lacks the goo_result_process

I did a fresh clone of the repo and the function is never declared while used in the Google and Bing search.
However, it is declared in the python3 version of dnsrecon.py : 

https://github.com/darkoperator/dnsrecon/blob/986e8a774b79015e2042252d4256994e1aec2409/dnsrecon.py#L490

`def goo_result_process(res, found_hosts):
    """
    This function processes the results returned from the Google Search and does
    an A and AAAA query for the IP of the found host. Prints and returns a dictionary
    with all the results found.
    """
    returned_records = []
    for sd in found_hosts:
        for sdip in res.get_ip(sd):
            if re.search(r'^A',sdip[0]):
                print_status('\t {0} {1} {2}'.format(sdip[0], sdip[1], sdip[2]))
            
                returned_records.extend([{'type':sdip[0], 'name':sdip[1], \
                'address':sdip[2]
                }])
    print_good("{0} Records Found".f`

**Comment by darkoperator** [comment] 2018-03-04 17:07
What parameters are you using?

**Comment by darkoperator** [comment] 2018-03-04 18:42
Pushed a fix for it, dont run it often because it is easy to detect as Google will mark your IP as a bot, Bing is safer on that respect.

**Comment by R3nt0n** [comment] 2018-04-17 21:39
I diff both versions of **`dnsrecon.py`** (github and system's preinstalled) and here we have the two differences that returns:

- Github version:
```
(1041)  goo_rcd = se_result_process(res, scrape_google(domain))
(1051)  bing_rcd = se_result_process(res, scrape_google(domain))
```

- Preinstalled version:
```
(1041)  goo_rcd = goo_result_process(res, scrape_google(domain))
(1051)  bing_rcd = goo_result_process(res, scrape_bing(domain))
```

Also, maybe there's a little mistake in the **`bing`**'s part (using **`scrape_google`**), or maybe yo do it on purpose for some reason. Anyway, I hope it helps...

Thank you for this tool!

**Comment by darkoperator** [comment] 2018-04-30 23:47
Pre-Installed? Kali linux clones and modifies a bit the version from github once I do a release, Do you mean Kali?

**Comment by R3nt0n** [comment] 2018-05-02 13:08
Yes, I mean Kali, sorry if it was ambiguous.  The point is, the `goo_result_process` doesn't exists, so if I change the preins version to `se_result_process`, it works fine.

But, my question is about the Github version, the version that you can control: It is right that both functions uses `scrape_google()`? Shouldn't `bing_rcd` use `scrape_bing()`?

**Closed** 2020-06-18 21:13 UTC
