### ISSUE TITLE
[Bug] False positive in TLD research

### ISSUE THREAD

**Issue by SimoneCagol** [darkoperator/dnsrecon#213] opened 2022-02-28 11:21 UTC
**Bug**
False positive in TLD research

**Description**
Some second level domains return always a DNS resolution (ex. ae.xxx).

Moreover, I think to have identify an issue in the way the second levels tlds are created, since actually the program is trying always only 32 combinations, and using always only the first 32 elements of the cctld array. Maybe two nested for cycle are a better options for this purpose.

Attempt 1 | Attempt 2 
--- | --- 
Trying: ***.ac.info |Trying: ***.ac.mil
Trying: ***.ad.online|	Trying: ***.ad.mobi
Trying: ***.ae.name|	Trying: ***.ae.int
Trying: ***.af.cloud|	Trying: ***.af.name
...|...
Trying: ***.bm.pro|	Trying: ***.bm.co
Trying: ***.bn.mobi|	Trying: ***.bn.pro
Trying: ***.bo.gov|	Trying: ***.bo.info
Trying: ***.bq.xxx|	Trying: ***.bq.museum

**To Reproduce**
```
nslookup aaaaaaaaabbbbbbbbbbbbcccccccccccdddddddddd.ae.xxx
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	aaaaaaaaabbbbbbbbbbbbcccccccccccdddddddddd.ae.xxx
Address: 64.190.62.111
```

**Comment by L1ghtn1ng** [comment] 2022-04-10 23:56
I really do not follow or see what the issue is here. Can you make it clear what the issue is?

**Comment by Frapava** [comment] 2022-04-11 07:05
I think that @SimoneCagol here identified two different problems:
The first one is the fact that for some second level combinations return always the same DNS resolution, despite the hostnames exist or not. In the example, if you try to execute the nslookup of ae.xxx, abcd.ae.xxx or example.ae.xxx, the result will not change.

````
nslookup abcd.ae.xxx
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	abcd.ae.xxx
Address: 64.190.63.111`

nslookup example.ae.xxx
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	example.ae.xxx
Address: 64.190.63.111

nslookup ae.xxx
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	ae.xxx
Address: 64.190.63.111
````

The second problem regards the implementation of the second level TLDs brute force:
only the first 32 elements of the cctld array are used during the brute force, and all the others are never used. He suggested to implement a nested for cycle in order to use every possible combination of cctld and total_tlds instead of the zip function.

**Comment by McFacePunch** [comment] 2024-10-18 11:37
@SimoneCagol @frapava98 if either of you could attempt to validate the fix, that would be awesome. You can run it from the PR branch in my above comment

**Comment by L1ghtn1ng** [comment] 2024-10-18 15:34
or just pull from master as merged it :-)

**Comment by McFacePunch** [comment] 2024-10-18 21:49
> or just pull from master as merged it :-)

haha or that too

**Comment by frapava98** [comment] 2024-10-28 12:09
I created the PR https://github.com/darkoperator/dnsrecon/pull/322 with some improvements.

**Comment by McFacePunch** [comment] 2024-10-31 09:30
@L1ghtn1ng  i think this can close?

**Comment by L1ghtn1ng** [comment] 2024-10-31 09:45
Closed ☺️

**Closed** 2024-10-31 09:45 UTC
Labels: Help Wanted
